toolbar:
  - styleselect | bold italic | undo redo | numlist bullist
  - image | link
plugins:
  - image
  - link
  - lists

default:
  plugins:
    - image
    - link
    - lists

alternate:
  <<: *default
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table